### ISSUE TITLE
Add testing and CI

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/kubewarden-controller#5] opened 2021-02-04 23:31 UTC
The controller should have a minimum amount of tests to ensure that the core functionality works as expected and easily extendable when bugs arise so we avoid regressions.

**Comment by flavio** [comment] 2021-08-20 08:24
Closing as a duplicate of https://github.com/kubewarden/kubewarden-controller/issues/62

**Closed by flavio** 2021-08-20 08:24 UTC
Labels: ci
