### ISSUE TITLE
Audit Scanner Cronjob misconfiguration on Helm chart

### ISSUE THREAD

**Issue by brunorene** [kubewarden/kubewarden-controller#670] opened 2024-03-05 10:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I generated the Yamls the helm chart for kuberwarden-controller outputs and noticed an issue. For the Audit Scanner Cronjob's command we have 

```
- --disable-store
- false
```

where the Yaml parser fails because it tries to create a Boolean for `false` on a slice that only accepts strings.

### Expected Behavior

It should generate:

```
- --disable-store
- "false"
```

### Environment

```markdown
- OS: Linux
- Architecture: amd64
```

**Comment by flavio** [comment] 2024-03-05 11:46
Closing as a duplicate of https://github.com/kubewarden/helm-charts/issues/390.

It has been fixed with RC2

**Closed by flavio** 2024-03-05 11:46 UTC
